/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CriarRouteImport } from './routes/criar'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SucessoIdRouteImport } from './routes/sucesso.$id'
import { Route as OfertaIdRouteImport } from './routes/oferta.$id'
import { Route as CriarOrderIdRouteImport } from './routes/criar.$orderId'
import { Route as CheckoutIdRouteImport } from './routes/checkout.$id'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as CriarPlanoPlanSlugRouteImport } from './routes/criar.plano.$planSlug'
import { Route as ApiZipOrderIdRouteImport } from './routes/api/zip.$orderId'
import { Route as ApiPublicAsaasWebhookRouteImport } from './routes/api/public/asaas-webhook'

const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarRoute = CriarRouteImport.update({
  id: '/criar',
  path: '/criar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SucessoIdRoute = SucessoIdRouteImport.update({
  id: '/sucesso/$id',
  path: '/sucesso/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertaIdRoute = OfertaIdRouteImport.update({
  id: '/oferta/$id',
  path: '/oferta/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarOrderIdRoute = CriarOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => CriarRoute,
} as any)
const CheckoutIdRoute = CheckoutIdRouteImport.update({
  id: '/checkout/$id',
  path: '/checkout/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const CriarPlanoPlanSlugRoute = CriarPlanoPlanSlugRouteImport.update({
  id: '/plano/$planSlug',
  path: '/plano/$planSlug',
  getParentRoute: () => CriarRoute,
} as any)
const ApiZipOrderIdRoute = ApiZipOrderIdRouteImport.update({
  id: '/api/zip/$orderId',
  path: '/api/zip/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAsaasWebhookRoute = ApiPublicAsaasWebhookRouteImport.update({
  id: '/api/public/asaas-webhook',
  path: '/api/public/asaas-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/criar': typeof CriarRouteWithChildren
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/criar/$orderId': typeof CriarOrderIdRoute
  '/oferta/$id': typeof OfertaIdRoute
  '/sucesso/$id': typeof SucessoIdRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
  '/api/zip/$orderId': typeof ApiZipOrderIdRoute
  '/criar/plano/$planSlug': typeof CriarPlanoPlanSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/criar': typeof CriarRouteWithChildren
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/criar/$orderId': typeof CriarOrderIdRoute
  '/oferta/$id': typeof OfertaIdRoute
  '/sucesso/$id': typeof SucessoIdRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
  '/api/zip/$orderId': typeof ApiZipOrderIdRoute
  '/criar/plano/$planSlug': typeof CriarPlanoPlanSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/criar': typeof CriarRouteWithChildren
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/criar/$orderId': typeof CriarOrderIdRoute
  '/oferta/$id': typeof OfertaIdRoute
  '/sucesso/$id': typeof SucessoIdRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
  '/api/zip/$orderId': typeof ApiZipOrderIdRoute
  '/criar/plano/$planSlug': typeof CriarPlanoPlanSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/criar'
    | '/login'
    | '/planos'
    | '/admin'
    | '/checkout/$id'
    | '/criar/$orderId'
    | '/oferta/$id'
    | '/sucesso/$id'
    | '/api/public/asaas-webhook'
    | '/api/zip/$orderId'
    | '/criar/plano/$planSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/criar'
    | '/login'
    | '/planos'
    | '/admin'
    | '/checkout/$id'
    | '/criar/$orderId'
    | '/oferta/$id'
    | '/sucesso/$id'
    | '/api/public/asaas-webhook'
    | '/api/zip/$orderId'
    | '/criar/plano/$planSlug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/criar'
    | '/login'
    | '/planos'
    | '/_authenticated/admin'
    | '/checkout/$id'
    | '/criar/$orderId'
    | '/oferta/$id'
    | '/sucesso/$id'
    | '/api/public/asaas-webhook'
    | '/api/zip/$orderId'
    | '/criar/plano/$planSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CriarRoute: typeof CriarRouteWithChildren
  LoginRoute: typeof LoginRoute
  PlanosRoute: typeof PlanosRoute
  CheckoutIdRoute: typeof CheckoutIdRoute
  OfertaIdRoute: typeof OfertaIdRoute
  SucessoIdRoute: typeof SucessoIdRoute
  ApiPublicAsaasWebhookRoute: typeof ApiPublicAsaasWebhookRoute
  ApiZipOrderIdRoute: typeof ApiZipOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar': {
      id: '/criar'
      path: '/criar'
      fullPath: '/criar'
      preLoaderRoute: typeof CriarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sucesso/$id': {
      id: '/sucesso/$id'
      path: '/sucesso/$id'
      fullPath: '/sucesso/$id'
      preLoaderRoute: typeof SucessoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oferta/$id': {
      id: '/oferta/$id'
      path: '/oferta/$id'
      fullPath: '/oferta/$id'
      preLoaderRoute: typeof OfertaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar/$orderId': {
      id: '/criar/$orderId'
      path: '/$orderId'
      fullPath: '/criar/$orderId'
      preLoaderRoute: typeof CriarOrderIdRouteImport
      parentRoute: typeof CriarRoute
    }
    '/checkout/$id': {
      id: '/checkout/$id'
      path: '/checkout/$id'
      fullPath: '/checkout/$id'
      preLoaderRoute: typeof CheckoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/criar/plano/$planSlug': {
      id: '/criar/plano/$planSlug'
      path: '/plano/$planSlug'
      fullPath: '/criar/plano/$planSlug'
      preLoaderRoute: typeof CriarPlanoPlanSlugRouteImport
      parentRoute: typeof CriarRoute
    }
    '/api/zip/$orderId': {
      id: '/api/zip/$orderId'
      path: '/api/zip/$orderId'
      fullPath: '/api/zip/$orderId'
      preLoaderRoute: typeof ApiZipOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/asaas-webhook': {
      id: '/api/public/asaas-webhook'
      path: '/api/public/asaas-webhook'
      fullPath: '/api/public/asaas-webhook'
      preLoaderRoute: typeof ApiPublicAsaasWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface CriarRouteChildren {
  CriarOrderIdRoute: typeof CriarOrderIdRoute
  CriarPlanoPlanSlugRoute: typeof CriarPlanoPlanSlugRoute
}

const CriarRouteChildren: CriarRouteChildren = {
  CriarOrderIdRoute: CriarOrderIdRoute,
  CriarPlanoPlanSlugRoute: CriarPlanoPlanSlugRoute,
}

const CriarRouteWithChildren = CriarRoute._addFileChildren(CriarRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CriarRoute: CriarRouteWithChildren,
  LoginRoute: LoginRoute,
  PlanosRoute: PlanosRoute,
  CheckoutIdRoute: CheckoutIdRoute,
  OfertaIdRoute: OfertaIdRoute,
  SucessoIdRoute: SucessoIdRoute,
  ApiPublicAsaasWebhookRoute: ApiPublicAsaasWebhookRoute,
  ApiZipOrderIdRoute: ApiZipOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
